Android - Fix refresh token failing due to missing serialization (#22463)
# Pull Request

- Fixes: #22461

## Summary

Added some debug logs for auth failures and turned out the refresh token REST call is throwing:

```
java.lang.IllegalArgumentException: Unable to create @Body converter for class com.nabla.sdk.core.data.auth.RestRefreshToken (parameter #1)
```

Since the refacto of gradle coventions we missed moving the kotlinx.serialization plugin from core to the new `android-library` convention plugin, which results in missing serialization for the REST body request and thus a retrofit call failure.


Added the missing plugin to fix the issue, will write a post mortem later for how we missed such a bug and how to mitigate in the future.